# Generated by Django 4.1.7 on 2023-04-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dog',
            name='breed',
            field=models.CharField(default='dog', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dog',
            name='description',
            field=models.TextField(default='I am a dog', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dog',
            name='name',
            field=models.CharField(default='Dog', max_length=100),
            preserve_default=False,
        ),
    ]
