# Generated by Django 4.1.7 on 2023-04-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_toy'),
    ]

    operations = [
        migrations.AddField(
            model_name='toy',
            name='toy_name',
            field=models.CharField(choices=[('B', 'Bone'), ('S', 'Stuffed Animal'), ('T', 'Tennis Ball')], default='B', max_length=1, verbose_name='Toy'),
        ),
    ]
